### ISSUE TITLE
Focus Tracker don't instll via Obsidian 

### ISSUE THREAD

**Issue by marcosyonaware** [jeetsukumaran/obsidian-focus-tracker#1]
Message Failed to Install Focus Tracker

Where are logs for installation?

My Obsidan:
Linux Fedora 40
Current version : v1.6.3

![Ynwr_2024-06-11_15-12](https://github.com/jeetsukumaran/obsidian-focus-tracker/assets/42282264/e7061e49-d91d-43ed-abe2-040cfb1f9474)
![Ynwr_2024-06-11_15-12_1](https://github.com/jeetsukumaran/obsidian-focus-tracker/assets/42282264/7e0f59a5-c3de-4f59-b228-bdafe7ee3e1b)
![Ynwr_2024-06-11_15-13](https://github.com/jeetsukumaran/obsidian-focus-tracker/assets/42282264/2aaa548d-3496-4c83-9687-8d38f3de3c17)

**Comment by jeetsukumaran** [comment]
This should be fixed now. Tags were not pushed :)
